"""Initial migration with clean models

Revision ID: fcb076b0fd98
Revises: 
Create Date: 2025-08-06 22:26:53.268514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb076b0fd98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('carboidratos_100g', sa.Float(), nullable=False),
    sa.Column('proteinas_100g', sa.Float(), nullable=False),
    sa.Column('gorduras_100g', sa.Float(), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=True),
    sa.Column('source_api_id', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_api_id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_consulta', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes_nutri', sa.Text(), nullable=True),
    sa.Column('link_videochamada', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_alimentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(length=150), nullable=False),
    sa.Column('objetivo_calorico_final', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('nome_refeicao', sa.String(length=100), nullable=False),
    sa.Column('horario_sugerido', sa.String(length=50), nullable=True),
    sa.Column('meta_carboidratos_g', sa.Float(), nullable=True),
    sa.Column('meta_proteinas_g', sa.Float(), nullable=True),
    sa.Column('meta_gorduras_g', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['plano_alimentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refeicao_id', sa.Integer(), nullable=False),
    sa.Column('nome_alimento', sa.String(length=200), nullable=False),
    sa.Column('marca_alimento', sa.String(length=150), nullable=True),
    sa.Column('quantidade_g', sa.Float(), nullable=False),
    sa.Column('medida_caseira', sa.String(length=100), nullable=True),
    sa.Column('substituicoes', sa.Text(), nullable=True),
    sa.Column('carboidratos_g', sa.Float(), nullable=False),
    sa.Column('proteinas_g', sa.Float(), nullable=False),
    sa.Column('gorduras_g', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refeicao_id'], ['refeicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_refeicao')
    op.drop_table('refeicao')
    op.drop_table('plano_alimentar')
    op.drop_table('consulta')
    op.drop_table('paciente')
    op.drop_table('alimento')
    # ### end Alembic commands ###
