# .github/workflows/build-windows-exe.yml

name: Build Windows Executable

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Configura o MSYS2 e instala o GTK3,
      # adicionando as bibliotecas necessárias ao PATH do sistema.
      - name: Set up MSYS2 and install GTK3
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gtk3

      # Este passo agora usa o Python principal (que tem o pip),
      # pois não estamos mais forçando o shell do msys2.
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # O PyInstaller também usará o Python principal,
      # mas encontrará as DLLs do GTK porque o MSYS2 as adicionou ao PATH.
      - name: Build executable with PyInstaller
        run: pyinstaller --name NutriPro --onefile --windowed --add-data "templates;templates" --add-data "static;static" --paths "C:/msys64/mingw64/bin" run.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NutriPro-windows-executable
          path: dist/NutriPro.exe