# .github/workflows/build-windows-exe.yml

name: Build Windows Executable

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ---- PASSO NOVO ----
      # Instala o GTK+3 Runtime usando o gerenciador de pacotes do Windows, o Chocolatey.
      # O "-y" no final confirma a instalação automaticamente.
      - name: Install GTK+3 Runtime
        run: choco install gtk3 --no-progress -y

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---- COMANDO MODIFICADO ----
      # Adicionamos a flag --paths para dizer ao PyInstaller onde encontrar as DLLs do GTK+.
      # Isso faz com que ele inclua essas bibliotecas essenciais dentro do .exe final.
      - name: Build executable with PyInstaller
        run: pyinstaller --name NutriPro --onefile --windowed --add-data "templates;templates" --add-data "static;static" --paths "C:\ProgramData\chocolatey\lib\gtk3\tools\gtk-runtime\bin" run.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NutriPro-windows-executable
          path: dist/NutriPro.exe