# .github/workflows/build-windows-exe.yml

name: Build Windows Executable

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ---- ALTERAÇÃO 1 ----
      # Corrigido o nome do pacote de 'gtk3' para 'gtk3-runtime'.
      - name: Install GTK+3 Runtime
        run: choco install gtk3-runtime --no-progress -y

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---- ALTERAÇÃO 2 ----
      # Corrigido o caminho para refletir o novo nome do pacote 'gtk3-runtime'.
      - name: Build executable with PyInstaller
        run: pyinstaller --name NutriPro --onefile --windowed --add-data "templates;templates" --add-data "static;static" --paths "C:\ProgramData\chocolatey\lib\gtk3-runtime\tools\gtk-runtime\bin" run.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NutriPro-windows-executable
          path: dist/NutriPro.exe